news/urls.py
from django.urls import path
from .views import home,*ArticoloDetailViewCB,ArticoloListView,GiornalistaDetailViewCB,GiornalistaListView,giornalisti_list_api,giornalisti_api,articoli_list_api,articoli_api

app_name="news"

urlpatterns = [
    path('', home, name="homeview"),
    path('articoli/<int:pk>',ArticoloDetailViewCB.as_view(),name="articolo_detail"),
    path('lista_articoli/',ArticoloListView.as_view(),name="lista_articoli"),
    path('giornalisti/<int:pk>',GiornalistaDetailViewCB.as_view(),name="giornalista_detail"),
    path('lista_giornalisti/',GiornalistaListView.as_view(),name="lista_giornalisti"),
    path('giornalisti_list_api/',giornalisti_list_api.as_view(),name="giornalisti_list_api"),
    path('giornalisti_api/',giornalisti_api.as_view(),name="giornalisti_api"),
    path('articoli_list_api/',articoli_list_api,name="articoli_list_api"),
    path('articoli_api/',articoli_api,name="articoli_api"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, variabili, chi_siamo, index, welcome, lista
app_name="prima_app"
urlpatterns=[
    path('homepage', homepage,name='homepage'),
    path('welcome/', welcome,name='welcome'),
    path('lista/', lista,name='lista'),
    path('chi_siamo/', chi_siamo,name='chi_siamo'),
    path('variabili/', variabili,name='variabili'),
    path('', index,name='index'),
]   

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_generale

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls", namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls", namespace="seconda_app")),
    path('',index_generale, name="index_generale"),
    path('news/',include("news.urls", namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls", namespace="prova_pratica_1")),
    path('prova_pratica_0/',include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('prova_pratica_2/',include("prova_pratica_2.urls", namespace="prova_pratica_2")),
]

prova_pratica_0/urls.py
from django.urls import path
from prova_pratica_0.views import somma,index3,media

app_name="prova_pratica_0"
urlpatterns=[
    path('', index3, name='index3'),
    path('somma',somma,name='somma'),
    path('media',media,name='media')

]

prova_pratica_1/urls.py
from django.urls import path
from prova_pratica_1.views import view_a, view_b, view_c
app_name="prova_pratica_1"
urlpatterns=[
    path("view_a/",view_a,name="view_a"),
    path("view_b/",view_b,name="view_b"),
    path("view_c/",view_c,name='view_c'),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if, if_else_elif, es_for, index2
app_name="seconda_app"
urlpatterns=[
    path("es_if",es_if,name="es_if"),
    path("if_else_elif",if_else_elif,name="if_else_elif"),
    path("es_for",es_for,name="es_for"),
    path('index2/',index2, name='index2'),
]

templates/base.html
{% load static %}
<!doctype html>                                              
<html lang="en">
  <head>                                          
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">primo progetto <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                prima_app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">benvenuto nella homepage</a>
                <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">variabili</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  seconda_app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">homepage</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">if else elif</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">es for</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  news
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 
                  <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">lista_articoli</a>
                  <a class="dropdown-item" href="{% url 'news:lista_giornalisti'%}">lista_giornalisti</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  prova_pratica_0
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'prova_pratica_0:somma'%}">somma</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_0:media'%}">media</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  prova_pratica_1
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:view_a'%}">view_a</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:view_b'%}">view_b</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:view_c'%}">view_c</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  prova_pratica_2
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'prova_pratica_2:view_lista_targhe'%}">view_a</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_2:view_b'%}">view_b</a>
                </div>
              </li>
          </ul>
        </div>
      </nav>
      <div class="container my-4">
       {% block content %}
       {% endblock content %}
       {% block script %}
       {% endblock script %}
      </div>

  </body>
</html>

templates/index_generale.html
{% extends "base.html" %}
{% block title%}{{block.super}} | index_generale {%endblock title%}

{%block content%}
    <ol>
        <li><a href="/admin">admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">prima_app</a></li>    
        <li><a href="{% url 'seconda_app:index2'%}">seconda_app</a></li> 
       
      {% comment %}   <li><a href="{% url 'prova_pratica_1:index'%}">prova_pratica_1</a></li>   {% endcomment %}
    </ol>
{%endblock content%}